# fly.toml app configuration file generated for nightscout-ferretdb on 2024-04-13T22:55:43+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nsferretdb'
primary_region = 'ams'

[build]
  image = 'ghcr.io/ferretdb/ferretdb'

[http_service]
  internal_port = 27017
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 27017

[[services.ports]]
    port = 27017

[[vm]]
  size = 'shared-cpu-1x'
